/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RedPacketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_RECIPIENTS"
      | "TOTAL_AMOUNT"
      | "claimRedPacket"
      | "claimedAmount"
      | "claimedCount"
      | "claimers"
      | "deposit"
      | "emergencyWithdraw"
      | "getClaimers"
      | "getContractBalance"
      | "getRedPacketInfo"
      | "hasClaimed"
      | "owner"
      | "remainingAmount"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RedPacketClaimed"
      | "RedPacketCreated"
      | "RedPacketFinished"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_RECIPIENTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRedPacket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimedAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRedPacketInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remainingAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_RECIPIENTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRedPacket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedPacketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remainingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedPacketClaimedEvent {
  export type InputTuple = [claimer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [claimer: string, amount: bigint];
  export interface OutputObject {
    claimer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedPacketCreatedEvent {
  export type InputTuple = [
    totalAmount: BigNumberish,
    maxRecipients: BigNumberish
  ];
  export type OutputTuple = [totalAmount: bigint, maxRecipients: bigint];
  export interface OutputObject {
    totalAmount: bigint;
    maxRecipients: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedPacketFinishedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RedPacket extends BaseContract {
  connect(runner?: ContractRunner | null): RedPacket;
  waitForDeployment(): Promise<this>;

  interface: RedPacketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_RECIPIENTS: TypedContractMethod<[], [bigint], "view">;

  TOTAL_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  claimRedPacket: TypedContractMethod<[], [void], "nonpayable">;

  claimedAmount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  claimedCount: TypedContractMethod<[], [bigint], "view">;

  claimers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getClaimers: TypedContractMethod<[], [string[]], "view">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getRedPacketInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        _remainingAmount: bigint;
        _claimedCount: bigint;
        _maxRecipients: bigint;
        _isFinished: boolean;
      }
    ],
    "view"
  >;

  hasClaimed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  remainingAmount: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_RECIPIENTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimRedPacket"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedAmount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimedCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getClaimers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRedPacketInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        _remainingAmount: bigint;
        _claimedCount: bigint;
        _maxRecipients: bigint;
        _isFinished: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "remainingAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RedPacketClaimed"
  ): TypedContractEvent<
    RedPacketClaimedEvent.InputTuple,
    RedPacketClaimedEvent.OutputTuple,
    RedPacketClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RedPacketCreated"
  ): TypedContractEvent<
    RedPacketCreatedEvent.InputTuple,
    RedPacketCreatedEvent.OutputTuple,
    RedPacketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RedPacketFinished"
  ): TypedContractEvent<
    RedPacketFinishedEvent.InputTuple,
    RedPacketFinishedEvent.OutputTuple,
    RedPacketFinishedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RedPacketClaimed(address,uint256)": TypedContractEvent<
      RedPacketClaimedEvent.InputTuple,
      RedPacketClaimedEvent.OutputTuple,
      RedPacketClaimedEvent.OutputObject
    >;
    RedPacketClaimed: TypedContractEvent<
      RedPacketClaimedEvent.InputTuple,
      RedPacketClaimedEvent.OutputTuple,
      RedPacketClaimedEvent.OutputObject
    >;

    "RedPacketCreated(uint256,uint256)": TypedContractEvent<
      RedPacketCreatedEvent.InputTuple,
      RedPacketCreatedEvent.OutputTuple,
      RedPacketCreatedEvent.OutputObject
    >;
    RedPacketCreated: TypedContractEvent<
      RedPacketCreatedEvent.InputTuple,
      RedPacketCreatedEvent.OutputTuple,
      RedPacketCreatedEvent.OutputObject
    >;

    "RedPacketFinished()": TypedContractEvent<
      RedPacketFinishedEvent.InputTuple,
      RedPacketFinishedEvent.OutputTuple,
      RedPacketFinishedEvent.OutputObject
    >;
    RedPacketFinished: TypedContractEvent<
      RedPacketFinishedEvent.InputTuple,
      RedPacketFinishedEvent.OutputTuple,
      RedPacketFinishedEvent.OutputObject
    >;
  };
}
